spring:
  application:
    name: "configserver"
  profiles:
     active: git
   # active: git
  cloud:
    config:
      server:
       # native:
         # search-loactions: "classpath:/config"
        #  search-locations: "file:///Users//cihancelik//config"
        git:
         uri: "https://github.com/cihancelik7/SpringCloud.git"
         default-label: main
         timeout: 5
         clone-on-start: true
         force-pull: true


server:
  port: 8071